name: Create Instance
run-name: Create '{% raw %}${{ inputs.INSTANCE_NAME }}{% endraw %}' on '{% raw %}${{ inputs.EDX_PLATFORM_VERSION }}{% endraw %}'

on:
  workflow_dispatch:
    inputs:
      INSTANCE_NAME:
        description: "Instance to create"
        type: string
      PLATFORM_NAME:
        description: "Platform name"
        default: "My Open edX Instance"
        type: string
      INSTANCE_TEMPLATE_REPOSITORY:
        description: "Repository containing the instance template"
        default: "https://github.com/open-craft/phd-cluster-template.git"
        type: string
      EDX_PLATFORM_REPOSITORY:
        description: "Repository to clone the edx-platform from"
        default: "https://github.com/openedx/edx-platform.git"
        type: string
      EDX_PLATFORM_VERSION:
        description: "Version of the edx-platform to use"
        default: "release/teak"
        type: string
      TUTOR_VERSION:
        description: "Version of the tutor to use"
        default: "{{ cookiecutter.tutor_version }}"
        type: string
      PHD_CLI_VERSION:
        description: "PHD CLI version"
        default: "{{ cookiecutter.phd_cluster_template_version }}"
        type: string
      RUNNER_WORKFLOW_LABEL:
        description: 'The label of the runner workflow to run'
        required: false
        default: "{{ cookiecutter.runner_workflow_label }}"
        type: string

jobs:
  create-instance:
    permissions:
      contents: write
    name: Create Instance
    uses: open-craft/phd-cluster-template/.github/workflows/create-instance.yml@main
    secrets:
      TERRAFORM_SECRETS: "{% raw %}${{ secrets.TERRAFORM_SECRETS }}{% endraw %}"
      PHD_DOCKER_REGISTRY_CREDENTIALS: "{% raw %}${{ secrets.PHD_DOCKER_REGISTRY_CREDENTIALS }}{% endraw %}"
      PHD_MYSQL_HOST: "{% raw %}${{ secrets.PHD_MYSQL_HOST }}{% endraw %}"
      PHD_MYSQL_PORT: "{% raw %}${{ secrets.PHD_MYSQL_PORT }}{% endraw %}"
      PHD_MYSQL_ROOT_USER: "{% raw %}${{ secrets.PHD_MYSQL_ROOT_USER }}{% endraw %}"
      PHD_MYSQL_ROOT_PASSWORD: "{% raw %}${{ secrets.PHD_MYSQL_ROOT_PASSWORD }}{% endraw %}"
      PHD_MONGODB_HOST: "{% raw %}${{ secrets.PHD_MONGODB_HOST }}{% endraw %}"
      PHD_MONGODB_PORT: "{% raw %}${{ secrets.PHD_MONGODB_PORT }}{% endraw %}"
      PHD_MONGODB_PROVIDER: "{% raw %}${{ secrets.PHD_MONGODB_PROVIDER }}{% endraw %}"
      PHD_MONGODB_CLUSTER_ID: "{% raw %}${{ secrets.PHD_MONGODB_CLUSTER_ID }}{% endraw %}"
      PHD_DIGITALOCEAN_TOKEN: "{% raw %}${{ secrets.PHD_DIGITALOCEAN_TOKEN }}{% endraw %}"
      PHD_STORAGE_TYPE: "{% raw %}${{ secrets.PHD_STORAGE_TYPE }}{% endraw %}"
      PHD_STORAGE_REGION: "{% raw %}${{ secrets.PHD_STORAGE_REGION }}{% endraw %}"
      PHD_STORAGE_ACCESS_KEY_ID: "{% raw %}${{ secrets.PHD_STORAGE_ACCESS_KEY_ID }}{% endraw %}"
      PHD_STORAGE_SECRET_ACCESS_KEY: "{% raw %}${{ secrets.PHD_STORAGE_SECRET_ACCESS_KEY }}{% endraw %}"
      SSH_PRIVATE_KEY: "{% raw %}${{ secrets.SSH_PRIVATE_KEY }}{% endraw %}"
    with:
      INSTANCE_NAME: "{% raw %}${{ inputs.INSTANCE_NAME }}{% endraw %}"
      PLATFORM_NAME: "{% raw %}${{ inputs.PLATFORM_NAME }}{% endraw %}"
      INSTANCE_TEMPLATE_REPOSITORY: "{% raw %}${{ inputs.INSTANCE_TEMPLATE_REPOSITORY }}{% endraw %}"
      EDX_PLATFORM_REPOSITORY: "{% raw %}${{ inputs.EDX_PLATFORM_REPOSITORY }}{% endraw %}"
      EDX_PLATFORM_VERSION: "{% raw %}${{ inputs.EDX_PLATFORM_VERSION }}{% endraw %}"
      TUTOR_VERSION: "{% raw %}${{ inputs.TUTOR_VERSION }}{% endraw %}"
      PHD_CLI_VERSION: "{% raw %}${{ inputs.PHD_CLI_VERSION }}{% endraw %}"
      RUNNER_WORKFLOW_LABEL: "{% raw %}${{ inputs.RUNNER_WORKFLOW_LABEL }}{% endraw %}"
