name: Delete Instance
run-name: Delete '{% raw %}${{ inputs.INSTANCE_NAME }}{% endraw %}'

on:
  workflow_dispatch:
    inputs:
      INSTANCE_NAME:
        description: "Instance to delete"
        type: string
      PHD_CLI_VERSION:
        description: "PHD CLI version"
        default: "{{ cookiecutter.phd_cluster_template_version }}"
        type: string
      RUNNER_WORKFLOW_LABEL:
        description: 'The label of the runner workflow to run'
        required: false
        default: "{{ cookiecutter.runner_workflow_label }}"
        type: string

jobs:
  delete-instance:
    permissions:
      contents: write
    name: Delete Instance
    uses: open-craft/phd-cluster-template/.github/workflows/delete-instance.yml@main
    secrets:
      TERRAFORM_SECRETS: "{% raw %}${{ secrets.TERRAFORM_SECRETS }}{% endraw %}"
      PHD_MYSQL_HOST: "{% raw %}${{ secrets.PHD_MYSQL_HOST }}{% endraw %}"
      PHD_MYSQL_PORT: "{% raw %}${{ secrets.PHD_MYSQL_PORT }}{% endraw %}"
      PHD_MYSQL_ROOT_USER: "{% raw %}${{ secrets.PHD_MYSQL_ROOT_USER }}{% endraw %}"
      PHD_MYSQL_ROOT_PASSWORD: "{% raw %}${{ secrets.PHD_MYSQL_ROOT_PASSWORD }}{% endraw %}"
      PHD_MONGODB_HOST: "{% raw %}${{ secrets.PHD_MONGODB_HOST }}{% endraw %}"
      PHD_MONGODB_PORT: "{% raw %}${{ secrets.PHD_MONGODB_PORT }}{% endraw %}"
      PHD_MONGODB_PROVIDER: "{% raw %}${{ secrets.PHD_MONGODB_PROVIDER }}{% endraw %}"
      PHD_MONGODB_CLUSTER_ID: "{% raw %}${{ secrets.PHD_MONGODB_CLUSTER_ID }}{% endraw %}"
      PHD_DIGITALOCEAN_TOKEN: "{% raw %}${{ secrets.PHD_DIGITALOCEAN_TOKEN }}{% endraw %}"
      PHD_STORAGE_TYPE: "{% raw %}${{ secrets.PHD_STORAGE_TYPE }}{% endraw %}"
      PHD_STORAGE_REGION: "{% raw %}${{ secrets.PHD_STORAGE_REGION }}{% endraw %}"
      PHD_STORAGE_ACCESS_KEY_ID: "{% raw %}${{ secrets.PHD_STORAGE_ACCESS_KEY_ID }}{% endraw %}"
      PHD_STORAGE_SECRET_ACCESS_KEY: "{% raw %}${{ secrets.PHD_STORAGE_SECRET_ACCESS_KEY }}{% endraw %}"
      SSH_PRIVATE_KEY: "{% raw %}${{ secrets.SSH_PRIVATE_KEY }}{% endraw %}"
    with:
      INSTANCE_NAME: "{% raw %}${{ inputs.INSTANCE_NAME }}{% endraw %}"
      PHD_CLI_VERSION: "{% raw %}${{ inputs.PHD_CLI_VERSION }}{% endraw %}"
      RUNNER_WORKFLOW_LABEL: "{% raw %}${{ inputs.RUNNER_WORKFLOW_LABEL }}{% endraw %}"
