name: Pre-commit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0  # Fetch all history for pre-commit hooks

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.14"

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2
        with:
          tofu_version: latest

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6
        with:
          failOnWarnings: true # Strict mode
          configFile: .github/.commitlintrc.mjs

      - name: Run pre-commit on PRs
        if: github.event_name == 'pull_request'
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          PCT_TFPATH: tofu

      - name: Run pre-commit on push to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          PCT_TFPATH: tofu
          SKIP: no-commit-to-branch
