---
# Configure ArgoCD admin password via bcrypt hash
# See: https://argo-cd.readthedocs.io/en/stable/operator-manual/admin/#local-users
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  # Bcrypt hash of the admin password
  admin.password: "{{ PHD_ARGO_ADMIN_PASSWORD_BCRYPT }}"
  # RFC3339 timestamp to force ArgoCD to reload the password
  admin.passwordMtime: "{{ PHD_ARGOCD_ADMIN_PASSWORD_MTIME }}"
