---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-executor
---
apiVersion: v1
kind: Secret
metadata:
  name: workflow-executor-token
  annotations:
    kubernetes.io/service-account.name: workflow-executor
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-executor-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtasks", "workflowtaskresults"]
    verbs: ["get", "list", "watch", "update", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-executor-binding
subjects:
  - kind: ServiceAccount
    name: workflow-executor
roleRef:
  kind: Role
  name: workflow-executor-role
  apiGroup: rbac.authorization.k8s.io
