apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: "mongodb-deprovision-{{ PHD_INSTANCE_NAME }}"
  namespace: "{{ PHD_INSTANCE_NAME }}"
spec:
  serviceAccountName: workflow-executor
  entrypoint: main
  arguments:
    parameters:
      - name: namespace
        value: "{{ PHD_INSTANCE_NAME }}"
      - name: database-name
        value: "{{ PHD_INSTANCE_MONGODB_DATABASE }}"
      - name: username
        value: "{{ PHD_INSTANCE_MONGODB_USERNAME }}"
      - name: mongodb-provider
        value: "{{ PHD_INSTANCE_MONGODB_PROVIDER }}"
      - name: mongodb-cluster-id
        value: "{{ PHD_INSTANCE_MONGODB_CLUSTER_ID }}"
      - name: digitalocean-token
        value: "{{ PHD_INSTANCE_DIGITALOCEAN_TOKEN }}"
      - name: atlas-public-key
        value: "{{ PHD_INSTANCE_ATLAS_PUBLIC_KEY }}"
      - name: atlas-private-key
        value: "{{ PHD_INSTANCE_ATLAS_PRIVATE_KEY }}"
      - name: atlas-project-id
        value: "{{ PHD_INSTANCE_ATLAS_PROJECT_ID }}"
      - name: atlas-cluster-name
        value: "{{ PHD_INSTANCE_ATLAS_CLUSTER_NAME }}"
  workflowTemplateRef:
    name: mongodb-deprovision-template
    clusterScope: true
