apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: "storage-provision-{{ PHD_INSTANCE_NAME }}"
  namespace: "{{ PHD_INSTANCE_NAME }}"
spec:
  serviceAccountName: workflow-executor
  entrypoint: main
  volumes:
    - name: service-account-token
      secret:
        secretName: workflow-executor-token
  arguments:
    parameters:
      - name: namespace
        value: "{{ PHD_INSTANCE_NAME }}"
      - name: bucket-name
        value: "{{ PHD_INSTANCE_STORAGE_BUCKET_NAME }}"
      - name: storage-type
        value: "{{ PHD_INSTANCE_STORAGE_TYPE }}"
      - name: region
        value: "{{ PHD_INSTANCE_STORAGE_REGION }}"
      - name: access-key-id
        value: "{{ PHD_INSTANCE_STORAGE_ACCESS_KEY_ID }}"
      - name: secret-access-key
        value: "{{ PHD_INSTANCE_STORAGE_SECRET_ACCESS_KEY }}"
      - name: endpoint-url
        value: "{{ PHD_INSTANCE_STORAGE_ENDPOINT_URL }}"
      - name: make-public
        value: "false"
  workflowTemplateRef:
    name: storage-provision-template
    clusterScope: true
