name: Build Service Image
run-name: Build '{% raw %}${{ inputs.SERVICE }}{% endraw %}' image for '{% raw %}${{ inputs.INSTANCE_NAME }}{% endraw %}' on '{% raw %}${{ inputs.STRAIN_REPOSITORY_BRANCH }}{% endraw %}' branch

on:
  workflow_dispatch:
    inputs:
      INSTANCE_NAME:
        description: "Instance to build"
        type: string
      SERVICE:
        description: "Service to build"
        default: "openedx"
        type: choice
        options:
          - openedx
          - mfe
      STRAIN_REPOSITORY_BRANCH:
        description: "Branch to clone the strain from"
        default: "main"
        type: string
      TUTOR_VERSION:
        description: "Version of the tutor to use"
        default: "v20.0.1"
        type: string
      PICASSO_VERSION:
        description: "Picasso version"
        default: "{{ cookiecutter.picasso_version }}"
        type: string
      PHD_CLUSTER_TEMPLATE_VERSION:
        description: "PHD cluster template version"
        default: "{{ cookiecutter.phd_cluster_template_version }}"
        type: string

jobs:
  build:
    name: Build with Picasso
    uses: eduNEXT/picasso/.github/workflows/build.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
      AWS_SECRET_ACCESS_KEY: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
      AWS_REGION: {% raw %}${{ secrets.AWS_REGION }}{% endraw %}
      SSH_PRIVATE_KEY: {% raw %}${{ secrets.SSH_PRIVATE_KEY }}{% endraw %}
    with:
      buildkit_parallelism: 4
      STRAIN_REPOSITORY: {% raw %}${{ github.repository }}{% endraw %}
      STRAIN_REPOSITORY_BRANCH: {% raw %}${{ inputs.STRAIN_REPOSITORY_BRANCH }}{% endraw %}
      STRAIN_PATH: "instances/{% raw %}${{ inputs.INSTANCE_NAME }}{% endraw %}"
      SERVICE: {% raw %}${{ inputs.SERVICE }}{% endraw %}
      USE_DYNAMIC_IMAGE_TAG: true
      ADD_RANDOM_SUFFIX_TO_IMAGE_TAG: true
      RANDOM_SUFFIX_LENGTH: "8"
      TIMESTAMP_FORMAT: "%Y%m%d"
      PICASSO_VERSION: {% raw %}${{ inputs.PICASSO_VERSION }}{% endraw %}
      PYTHON_VERSION: 3.12
      # Prevent updating the image tag in the config.yml -- it would cause two
      # commits as we commit other config changes later. We want to avoid confusion
      # and have a single commit for the whole config update.
      UPDATE_IMAGE_TAG_IN_REPO: false

  update-instance-config:
    name: Update Instance Config
    uses: open-craft/phd-cluster-template/.github/workflows/update-instance-config.yml@main
    permissions:
      contents: write
    secrets:
      SSH_PRIVATE_KEY: {% raw %}${{ secrets.SSH_PRIVATE_KEY }}{% endraw %}
    with:
      INSTANCE_NAME: {% raw %}${{ inputs.INSTANCE_NAME }}{% endraw %}
      SERVICE: {% raw %}${{ inputs.SERVICE }}{% endraw %}
      STRAIN_REPOSITORY: {% raw %}${{ github.repository }}{% endraw %}
      STRAIN_REPOSITORY_BRANCH: {% raw %}${{ inputs.STRAIN_REPOSITORY_BRANCH }}{% endraw %}
      TUTOR_VERSION: {% raw %}${{ inputs.TUTOR_VERSION }}{% endraw %}
      PICASSO_VERSION: {% raw %}${{ inputs.PICASSO_VERSION }}{% endraw %}
      PHD_CLUSTER_TEMPLATE_VERSION: {% raw %}${{ inputs.PHD_CLUSTER_TEMPLATE_VERSION }}{% endraw %}
