name: Build Service Image

on:
  workflow_call:
    inputs:
      INSTANCE_NAME:
        description: "Instance to build"
        required: true
        type: string
      SERVICE:
        description: "Service to build"
        required: true
        type: string
      STRAIN_REPOSITORY:
        description: "Repository containing the cluster/strains"
        required: true
        type: string
      STRAIN_REPOSITORY_BRANCH:
        description: "Branch to clone the strain from"
        required: true
        type: string
      TUTOR_VERSION:
        description: "Version of the tutor to use"
        required: true
        type: string
      PICASSO_VERSION:
        description: "Picasso version"
        required: true
        type: string
      PHD_CLI_VERSION:
        description: "PHD CLI version"
        required: true
        type: string
      RUNNER_WORKFLOW_LABEL:
        description: "The label of the runner workflow to run"
        required: false
        type: string
        default: "ubuntu-latest"
    outputs:
      image_name:
        description: "Full image name (repo/name:tag)"
        value: ${{ jobs.build.outputs.image_name }}
      image_tag:
        description: "Image tag only"
        value: ${{ jobs.build.outputs.image_tag }}
    secrets:
      SSH_PRIVATE_KEY:
        description: "Private SSH key for accessing private repositories"
        required: true

jobs:
  build:
    name: Build with Picasso
    uses: open-craft/picasso/.github/workflows/build.yml@gabor/add-ghcr-support
    permissions:
      packages: write
      contents: read
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    with:
      STRAIN_REPOSITORY: ${{ inputs.STRAIN_REPOSITORY }}
      STRAIN_REPOSITORY_BRANCH: ${{ inputs.STRAIN_REPOSITORY_BRANCH }}
      STRAIN_PATH: "instances/${{ inputs.INSTANCE_NAME }}"
      SERVICE: ${{ inputs.SERVICE }}
      IMAGE_TAG_PREFIX: "${{ inputs.INSTANCE_NAME }}-"
      USE_DYNAMIC_IMAGE_TAG: true
      ADD_RANDOM_SUFFIX_TO_IMAGE_TAG: true
      RANDOM_SUFFIX_LENGTH: "8"
      TIMESTAMP_FORMAT: "%Y%m%d"
      PICASSO_VERSION: ${{ inputs.PICASSO_VERSION }}
      PYTHON_VERSION: 3.12
      # Prevent updating the image tag in the config.yml -- it would cause two
      # commits as we commit other config changes later. We want to avoid confusion
      # and have a single commit for the whole config update.
      UPDATE_IMAGE_TAG_IN_REPO: false
      RUNNER_WORKFLOW_LABEL: ${{ inputs.RUNNER_WORKFLOW_LABEL }}

