name: Test Tooling

on:
  push:
    branches:
      - main
    paths:
      - "tooling/**"
      - ".github/workflows/test-tooling.yml"
  pull_request:
    branches:
      - main
    paths:
      - "tooling/**"
      - ".github/workflows/test-tooling.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: tooling
        run: uv sync --all-groups

      - name: Run tests
        working-directory: tooling
        env:
          PHD_CLUSTER_DOMAIN: test.example.com
        run: uv run pytest -v --cov=phd --cov-report=term --cov-report=xml

      - name: Run pylint
        working-directory: tooling
        env:
          PHD_CLUSTER_DOMAIN: test.example.com
        run: uv run pylint phd/

