name: Update Instance Config

on:
  workflow_dispatch:
    inputs:
      INSTANCE_NAME:
        description: "Instance to create"
        required: true
        type: string
      SERVICE:
        description: "Service to update"
        required: true
        type: string
      STRAIN_REPOSITORY:
        description: "The repository for strains to checkout. It should follow the format: ORGANIZATION/REPO"
        required: true
        type: string
      STRAIN_REPOSITORY_BRANCH:
        description: "Branch to clone the strain from"
        required: true
        type: string
      TUTOR_VERSION:
        description: "Version of the tutor to use"
        required: true
        type: string
      PICASSO_VERSION:
        description: "Picasso version"
        required: true
        type: string
      PHD_CLUSTER_TEMPLATE_VERSION:
        description: "PHD cluster template version"
        required: true
        type: string
      RUNNER_WORKFLOW_LABEL:
        description: "The label of the runner workflow to run"
        required: false
        type: string
        default: "ubuntu-24.04"

jobs:
  update-instance-config:
    runs-on: ${{ inputs.RUNNER_WORKFLOW_LABEL }}
    defaults:
      run:
        shell: bash
    env:
      TUTOR_ROOT: ${{ github.workspace }}/strains/instances/${{ inputs.INSTANCE_NAME }}
      TUTOR_PLUGINS_ROOT: ${{ github.workspace }}/strains/instances/${{ inputs.INSTANCE_NAME }}/plugins

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Setup SSH agent for private repositories cloning
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add GitHub to known hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Checkout Picasso repository for utility scripts
        uses: actions/checkout@v4
        with:
          repository: edunext/picasso
          ref: ${{ inputs.PICASSO_VERSION }}
          path: picasso

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install PHD CLI
        run: uv tool install git+https://github.com/open-craft/phd-cluster-template.git@${{ inputs.PHD_CLUSTER_TEMPLATE_VERSION }}#subdirectory=tooling

      - name: Checkout cluster repository for build configurations
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.STRAIN_REPOSITORY }}
          ref: ${{ inputs.STRAIN_REPOSITORY_BRANCH }}
          ssh-key: ${{ inputs.STRAIN_REPOSITORY != github.repository && secrets.SSH_PRIVATE_KEY || '' }}
          path: strains

      - name: Install necessary requirements for workflow scripts
        working-directory: ${{ github.workspace }}
        run: |
          pip install -r picasso/requirements/base.txt

      - name: Get Tutor Configurations from config.yml and set them as an environment variable
        working-directory: ${{ github.workspace }}
        env:
          REQUIRED_KEYS: TUTOR_VERSION
          OPTIONAL_KEYS: ""
          CONFIG_FILE: strains/instances/${{ inputs.INSTANCE_NAME }}/config.yml
          SCRIPT_PATH: picasso/.github/workflows/scripts/get_tutor_config.py
        run: |
          ENV_VARS=$(python $SCRIPT_PATH --config-file $CONFIG_FILE --required-keys $REQUIRED_KEYS --optional-keys $OPTIONAL_KEYS)
          echo "$ENV_VARS" >> $GITHUB_ENV

      - name: Install Tutor and its dependencies from the version specified in the config.yml
        run: |
          pip install git+https://github.com/overhangio/tutor.git@$TUTOR_VERSION
          tutor config save

      - name: Enable and install picasso plugin in Tutor environment
        run: |
          pip install git+https://github.com/eduNEXT/tutor-contrib-picasso@v0.2.0
          tutor plugins enable picasso

      - name: Execute picasso extra commands
        run: |
          tutor picasso run-extra-commands

      - name: Update ${{ inputs.SERVICE }} image tag
        working-directory: ${{ github.workspace }}
        env:
          SERVICE: ${{ inputs.SERVICE }}
          STRAIN_PATH: strains/instances/${{ inputs.INSTANCE_NAME }}
          CONFIG_FILE: strains/instances/${{ inputs.INSTANCE_NAME }}/config.yml
          SCRIPT_PATH: picasso/.github/workflows/scripts/dynamic_image_tag.py
        run: |
          git restore $CONFIG_FILE

          python $SCRIPT_PATH \
            --config-file "$CONFIG_FILE" \
            --service "$SERVICE" \
            --save-config "true" \
            --image-tag "$DYNAMIC_IMAGE_TAG"

          git add $CONFIG_FILE

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update service: $SERVICE image"
          fi

      - name: Update Tutor environment
        working-directory: ${{ github.workspace }}/strains
        env:
          INSTANCE_NAME: ${{ inputs.INSTANCE_NAME }}
          STRAIN_PATH: instances/${{ inputs.INSTANCE_NAME }}
          SCRIPT_PATH: ${{ github.workspace }}/picasso/.github/workflows/scripts/dynamic_image_tag.py
        run: |
          git add $STRAIN_PATH/env

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update tutor config for $INSTANCE_NAME image"
          fi

      - name: Push changes to remote repository
        working-directory: ${{ github.workspace }}/strains
        run: |
          if git diff --cached --quiet; then
            git pull origin ${{ inputs.STRAIN_REPOSITORY_BRANCH }} --rebase
            git push
          else
            echo "No changes to commit"
          fi
